run:
  skip-dirs:
    - _badges
    - cmd/scratch
    - internal/mysqlx

linters-settings:
  cyclop:
    max-complexity: 15
    package-average: 0.0
    skip-tests: true
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 3
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - paramTypeCombine
      - rangeValCopy
      - typeDefFirst
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/ewohltman/ephemeral-roles
  golint:
    min-confidence: 0.8
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - contextcheck
    - deadcode
    - dupl
    - execinquery
    - exhaustivestruct
    - exhaustruct
    - gci
    - gochecknoglobals
    - goerr113
    - gofumpt
    - golint
    - ifshort
    - interfacer
    - ireturn
    - maligned
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - tagliatelle
    - testpackage
    - varcheck
    - varnamelen
    - wastedassign
    - wrapcheck

issues:
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - cyclop
        - dupl
        - errcheck
        - errchkjson
        - forcetypeassert
        - gocyclo
        - gosec
